# Generated by Django 5.0.1 on 2024-04-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_members_delete_memberdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(related_name='labels', to='tasks.label'),
        ),
    ]
